export const ALL_CALL_LIST_REQUEST = "ALL_CALL_LIST_REQUEST";
export const ALL_CALL_LIST_SUCCESS = "ALL_CALL_LIST_SUCCESS";
export const ALL_CALL_LIST_FAILURE = "ALL_CALL_LIST_FAILURE";

export const CALL_DETAILS_BY_ID_REQUEST = "CALL_DETAILS_BY_ID_REQUEST";
export const CALL_DETAILS_BY_ID_SUCCESS = "CALL_DETAILS_BY_ID_SUCCESS";
export const CALL_DETAILS_BY_ID_FAILURE = "CALL_DETAILS_BY_ID_FAILURE";

export const PATCH_CALL_DETAILS_BY_ID_REQUEST = "PATCH_CALL_DETAILS_BY_ID_REQUEST";
export const PATCH_CALL_DETAILS_BY_ID_SUCCESS = "PATCH_CALL_DETAILS_BY_ID_SUCCESS";
export const PATCH_CALL_DETAILS_BY_ID_FAILURE = "PATCH_CALL_DETAILS_BY_ID_FAILURE";